In [ ]:
# NOTA:
# Este ejercicio usamos el dataset de Cancer de mama de Scikit-Learn
# https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html

# 0 Analizamos datos con la Maquina de Vectores y De Soportes

In [ ]:
# Estos sirven para analizar pocos datos con muchas caracteristicas

# El modelo SVM (Support Vector Machine, Máquina de Vectores de Soporte) es un algoritmo de aprendizaje supervisado utilizado principalmente para problemas de clasificación y regresión. Su objetivo es encontrar el hiperplano que mejor separa las diferentes clases en el espacio de características. Aquí hay algunas aplicaciones comunes de SVM:

# - Clasificación binaria: SVM se utiliza comúnmente para clasificar datos en dos clases. Por ejemplo, en problemas de detección de spam, SVM puede usarse para clasificar correos electrónicos como spam o no spam.
# - Clasificación multiclase: SVM también se puede extender para clasificar datos en más de dos clases. Por ejemplo, en reconocimiento de dígitos manuscritos, SVM puede usarse para clasificar los dígitos del 0 al 9.
# - Clasificación no lineal: SVM puede manejar eficazmente problemas de clasificación no lineales mediante el uso de funciones de kernel, que transforman los datos en un espacio dimensional superior donde es más fácil encontrar un hiperplano de separación lineal.
# - Regresión: Aunque SVM es más conocido por la clasificación, también puede utilizarse para problemas de regresión. En este caso, SVM encuentra un hiperplano que mejor se ajusta a los datos de entrenamiento de una manera que minimiza el error de regresión.
# - Detección de anomalías: SVM se puede utilizar para detectar anomalías en conjuntos de datos, como fraudes en transacciones financieras o fallos en sistemas.
# En resumen, SVM es un modelo versátil que se puede utilizar en una variedad de problemas de aprendizaje supervisado, especialmente cuando se trata de problemas de clasificación lineal o no lineal.

# 1 Importamos los datos

In [2]:
# 1.- IMportamos los datos
from sklearn import datasets
datos = datasets.load_breast_cancer(as_frame=True # Colocamos as_frame=True para cargarlo como ser de datos
                                    )

# 2.- Analizamos la informacion

In [4]:
# 2.0 Visualizamos los primero registros
datos.frame.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [5]:
# 2.2 Vemos los datos que tiene el dataset
# En este data set vemos que tiene 569 registros y no hay vacios
datos.frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [6]:
# 2.3 Confirmamos que no tenga datos vacios
# Vemos que todos estan en "0"
datos.frame.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [7]:
# 2.4 Vemos mas informacion sobre los registros
datos.frame.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [9]:
# 2.5 Vemos la forma que tienen los datos. 
datos.data.shape

(569, 30)

In [ ]:
# 2.5.1 Lo que nos dice es que tiene 569 Registros con 30 Caracteristicas
# o bien 30 columnas.

# 3. Separamos los datos de entradas y salidas para preparar el modelo

In [37]:
# 3.1 Separamos los datos
from sklearn.model_selection import train_test_split

x = datos.data
y = datos.target
x_ent, x_pruebas, y_ent, y_pruebas = train_test_split(x,y,test_size= .3)

# 4. Creamos el modelo SVM y probamos los Kernels y Gamas

In [13]:
# 4.1 Importamos el modelo Maquinas de vectores
from sklearn import svm
from sklearn import metrics


# 4.2 Usamos el modelo SVC Supported Vector Classifier
modelo = svm.SVC() 

# 4.3 Entrenamos el modelo
modelo.fit(x_ent,y_ent)

# 4.4 Hacemos unas predicciones
pedicciones = modelo.predict(x_pruebas)

print("Exactitud:", metrics.accuracy_score(y_pruebas, pedicciones))
print("Precicion:", metrics.precision_score(y_pruebas, pedicciones))

Exactitud: 0.9122807017543859
Precicion: 0.8782608695652174

In [19]:
# 4.5 Modificamos el codigo anterior para probar con los 3 Kernels
# y los valores de Gama para saber cual da mejor exactitud y precision
# 4.1 Importamos el modelo Maquinas de vectores
from sklearn import svm
from sklearn import metrics

# 4.1.1 Ponemos los kernels que transforman los datos para probarlos
kernels = ["linear","rbf","sigmoid"]
gamas = [1, .01, .001, .0001]

for kernel in kernels:
    for gama in gamas:

        # 4.2 Usamos el modelo SVC Supported Vector Classifier
        modelo = svm.SVC(kernel=kernel, gamma = gama) 

        # 4.3 Entrenamos el modelo
        modelo.fit(x_ent,y_ent)

        # 4.4 Hacemos unas predicciones
        pedicciones = modelo.predict(x_pruebas)

        print(f"Kernel {kernel} & Gama {gama} -> Exactitud:", metrics.accuracy_score(y_pruebas, pedicciones))
        print(f"Kernel {kernel} & Gama {gama} -> Precicion:", metrics.precision_score(y_pruebas, pedicciones))

Kernel linear & Gama 1 -> Exactitud: 0.9883040935672515
Kernel linear & Gama 1 -> Precicion: 0.9807692307692307
Kernel linear & Gama 0.01 -> Exactitud: 0.9883040935672515
Kernel linear & Gama 0.01 -> Precicion: 0.9807692307692307
Kernel linear & Gama 0.001 -> Exactitud: 0.9883040935672515
Kernel linear & Gama 0.001 -> Precicion: 0.9807692307692307
Kernel linear & Gama 0.0001 -> Exactitud: 0.9883040935672515
Kernel linear & Gama 0.0001 -> Precicion: 0.9807692307692307
Kernel rbf & Gama 1 -> Exactitud: 0.5964912280701754
Kernel rbf & Gama 1 -> Precicion: 0.5964912280701754
Kernel rbf & Gama 0.01 -> Exactitud: 0.5906432748538012
Kernel rbf & Gama 0.01 -> Precicion: 0.5941176470588235
Kernel rbf & Gama 0.001 -> Exactitud: 0.935672514619883
Kernel rbf & Gama 0.001 -> Precicion: 0.9595959595959596
Kernel rbf & Gama 0.0001 -> Exactitud: 0.9473684210526315
Kernel rbf & Gama 0.0001 -> Precicion: 0.9603960396039604
Kernel sigmoid & Gama 1 -> Exactitud: 0.5964912280701754
Kernel sigmoid & Gama 1 -> Precicion: 0.5964912280701754
Kernel sigmoid & Gama 0.01 -> Exactitud: 0.5964912280701754
Kernel sigmoid & Gama 0.01 -> Precicion: 0.5964912280701754
Kernel sigmoid & Gama 0.001 -> Exactitud: 0.5964912280701754
Kernel sigmoid & Gama 0.001 -> Precicion: 0.5964912280701754
Kernel sigmoid & Gama 0.0001 -> Exactitud: 0.5964912280701754
Kernel sigmoid & Gama 0.0001 -> Precicion: 0.5964912280701754

In [38]:
#NOTA : COn esto podemos ver que al kernel que mejor deio Precision y Exactitud
# Fue el "Lineal" y al que peor le fue con el conjunto de datos gue el Sigmoid
# por lo tanto lo usamos para nuestro modelo 

# 4.2 Usamos el modelo SVC Supported Vector Classifier
modelo = svm.SVC(kernel="linear") 

# 4.3 Entrenamos el modelo
modelo.fit(x_ent,y_ent)

# 4.4 Hacemos unas predicciones
pedicciones = modelo.predict(x_pruebas)

print(f"Kernel {kernel} & Gama {gama} -> Exactitud:", metrics.accuracy_score(y_pruebas, pedicciones))
print(f"Kernel {kernel} & Gama {gama} -> Precicion:", metrics.precision_score(y_pruebas, pedicciones))

Kernel sigmoid & Gama 0.0001 -> Exactitud: 0.9473684210526315
Kernel sigmoid & Gama 0.0001 -> Precicion: 0.9411764705882353

# 5.- Hacemos el reporte de clasificacion

In [40]:
# 5.1 Importamos las librerias
from sklearn.metrics import classification_report

print(classification_report(y_pruebas, pedicciones))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94        72
           1       0.94      0.97      0.96        99

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.95       171
weighted avg       0.95      0.95      0.95       171

In [41]:
# 5.2 Sacamos la matriz de confusion
from sklearn.metrics import confusion_matrix
import pandas as pd

pd.DataFrame( confusion_matrix(y_pruebas, pedicciones))

    0   1
0  66   6
1   3  96

In [ ]:
# 5.3 La matriz de confusion nos indica que de los :
#   67 - 0 estubieron incorrectors y
#   102 - 2 estuvieron mas clasificados